apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: python-helloworld-prod 
  namespace: prod
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      valueFiles:
      - values-prod.yaml 
    path: solutions/helm/python-helloworld 

    repoURL: https://github.com/udacity/nd064_course_1

    targetRevision: HEAD



apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: python-helloworld-prod 
  namespace: prod
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      valueFiles:
      - values-prod.yaml 
    path: solutions/helm/python-helloworld 

    repoURL: https://github.com/udacity/nd064_course_1

    targetRevision: HEAD