namespace:
  name: sandbox
 
service:
  port: 4111
  type: ClusterIP
  targetPort: 3111


image:
  repository: bjk1456/tech-trends 
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 1

resources:
  requests:
    cpu: 350m
    memory: 128Mi
  limit:
    memory: 256Mi 
    cpu: 500m

configmap:
  data: "version: alpine"