namespace:
  name: staging 
 
service:
  port: 5111
  type: ClusterIP

replicaCount: 3

resources:
  requests:
    cpu: 300m
    memory: 90Mi
  limit:
    memory: 128Mi 
    cpu: 500m


namespace:
  name: staging

replicaCount: 3

service:
  port: 5111
  protocol: TCP
  targetPort: 3111
  type: ClusterIP

image:
  repository: bjk1456/techtrends
  tag: latest
  pullPolicy: IfNotPresent

containerPort: 3111

livenessProbe:
  httpGet:
    path: /healthz
    port: 3111

readinessProbe:
  httpGet:
    path: /healthz
    port: 3111

resources:
  requests:
    cpu: "300m"
    memory: "90Mi"
  limits:
    cpu: "500m"
    memory: "128Mi"